// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Internal Infra Team"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/config/audit": {
            "get": {
                "description": "Returns the in-memory ring buffer of the last 500 CONFIG SET operations, including old value, new value, node address, and remote IP.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Config change audit log",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_operations.AuditEntry"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/config/diff": {
            "get": {
                "description": "Runs CONFIG GET * on every node and returns keys whose values differ across nodes. Only drifted keys are included in the response.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Cross-node config diff",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_operations.ConfigDiff"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "502": {
                        "description": "Node unreachable",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/config/set": {
            "post": {
                "description": "Applies CONFIG SET on a specific node and records the change in the audit log. Requires confirm:true in the request body.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Set a Redis config value",
                "parameters": [
                    {
                        "description": "CONFIG SET parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api_dto.ConfigSetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "confirm not set or invalid request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "502": {
                        "description": "Node unreachable",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/connections": {
            "get": {
                "description": "Runs CLIENT LIST on every Redis node, groups connections by source IP, and enriches each entry with Kubernetes Pod metadata (name, namespace, deployment) where available. Also reports which connected pods are CPU-throttled.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connections"
                ],
                "summary": "List client connections per node",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_connection.NodeConnections"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "502": {
                        "description": "No sentinel reachable",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "503": {
                        "description": "No master found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "504": {
                        "description": "Redis timeout",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/connections/analysis": {
            "get": {
                "description": "Aggregates Redis CLIENT LIST data across all Redis nodes and detects abnormal/suspicious connection patterns such as connection leaks, long-idle clients, and excessive connection usage. Returns cluster-wide summaries, top offenders, suspicious clients, and operational recommendations.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connections"
                ],
                "summary": "Analyze Redis client connections",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_connection.AnalysisResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "502": {
                        "description": "No sentinel reachable",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "503": {
                        "description": "No master found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "504": {
                        "description": "Redis timeout",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/connections/distribution": {
            "get": {
                "description": "Fetches INFO commandstats from every replica, classifies each command as read or write, and computes percentages. A replica is flagged as overloaded when it carries more than 80% of total cluster read traffic.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connections"
                ],
                "summary": "Read/write distribution per replica",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_connection.ReplicaDistribution"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "502": {
                        "description": "No sentinel reachable",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "503": {
                        "description": "No master found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "504": {
                        "description": "Redis timeout",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/diagnostics/locks": {
            "get": {
                "description": "Scans keys matching a pattern and returns those with no TTL or with a TTL exceeding the stale threshold. Useful for detecting leaked distributed locks.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "diagnostics"
                ],
                "summary": "Stale distributed lock detector",
                "parameters": [
                    {
                        "type": "string",
                        "default": "lock:*",
                        "description": "Key pattern to scan (default lock:*)",
                        "name": "pattern",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 300,
                        "description": "TTL in seconds above which a lock is considered stale; 0 = flag only keys with no TTL (default 300)",
                        "name": "stale_threshold",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_diagnostics.LockReport"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/diagnostics/memory": {
            "get": {
                "description": "Returns memory fragmentation, eviction rate, and persistence health for every cluster node.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "diagnostics"
                ],
                "summary": "Memory health report",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_diagnostics.MemoryReport"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/diagnostics/pipeline": {
            "get": {
                "description": "Collects EXECABORT error counts, rejected_calls, maximum input buffer size, and oversized pipeline client counts (qbuf \u003e 1 MiB) from every node.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "diagnostics"
                ],
                "summary": "Get pipeline and transaction stats per node",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_diagnostics.PipelineReport"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "502": {
                        "description": "No sentinel reachable",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "504": {
                        "description": "Redis timeout",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/diagnostics/slowlog": {
            "get": {
                "description": "Pulls SLOWLOG GET from all nodes (master + replicas), aggregates entries, and returns them sorted by execution time descending. Use the limit parameter to control how many entries are returned.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "diagnostics"
                ],
                "summary": "Get slow commands across cluster",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Max entries to return (default 50, max 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_diagnostics.SlowlogEntry"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid limit",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "502": {
                        "description": "No sentinel reachable",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "504": {
                        "description": "Redis timeout",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/events/stream": {
            "get": {
                "description": "Server-Sent Events stream of real-time Sentinel events (+sdown, -sdown, +odown, +failover-*). Connect and keep the connection open to receive events as they happen. Each event line is: ` + "`" + `event: sentinel\\ndata: {json}\\n\\n` + "`" + `.",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Live Sentinel event stream",
                "responses": {
                    "200": {
                        "description": "SSE stream",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Returns 200 OK when the process is alive. Used by Kubernetes liveness probe.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api_dto.HealthResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/keys/bigkeys": {
            "get": {
                "description": "Streams big keys found via non-blocking SCAN as Server-Sent Events. Each event is a KeyReport JSON object. A final \"summary\" event contains per-namespace aggregates.",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "keys"
                ],
                "summary": "Big key scanner (SSE)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Minimum key size in bytes to report (default 1048576)",
                        "name": "threshold_bytes",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "stream of SSE events",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/keys/hotkeys": {
            "get": {
                "description": "Returns the top-N keys by LFU access frequency. Requires maxmemory-policy to be an *-lfu variant.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "keys"
                ],
                "summary": "Hot key detector (LFU)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of hot keys to return (default 20)",
                        "name": "top",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_keys.HotKeyReport"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/keys/ttl-report": {
            "get": {
                "description": "Returns per-namespace percentage of keys without a TTL set.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "keys"
                ],
                "summary": "TTL health report",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_keys.NamespaceTTLReport"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ops/chaos/failover": {
            "post": {
                "description": "Triggers a failover without pre-checks. mode=sentinel sends SENTINEL FAILOVER directly; mode=pod deletes the named Redis pod via K8s to force failover. Requires confirm:true.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chaos"
                ],
                "summary": "Chaos failover trigger",
                "parameters": [
                    {
                        "description": "Chaos failover parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api_dto.ChaosFailoverRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_chaos.ChaosFailoverResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "confirm not set or invalid request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "503": {
                        "description": "No reachable sentinel or K8s unavailable",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ops/chaos/flush": {
            "post": {
                "description": "Deletes all keys matching the given pattern via SCAN+DEL on the master. Never calls FLUSHALL. Requires confirm:true.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chaos"
                ],
                "summary": "Pattern-scoped cluster flush",
                "parameters": [
                    {
                        "description": "Flush parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api_dto.FlushRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_chaos.FlushResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "confirm not set",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "502": {
                        "description": "Master unreachable",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ops/chaos/seed": {
            "post": {
                "description": "Generates configurable dummy keys on the master node. Supports string, hash, list, set, and zset types. Requires confirm:true.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chaos"
                ],
                "summary": "Seed dummy data",
                "parameters": [
                    {
                        "description": "Seed parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api_dto.SeedRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_chaos.SeedResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "confirm not set or invalid request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "502": {
                        "description": "Master unreachable",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ops/failover": {
            "post": {
                "description": "Performs a lag-check, selects the best replica, then triggers SENTINEL FAILOVER. Use dry_run:true to preview without executing. Requires confirm:true when dry_run is false.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Graceful failover",
                "parameters": [
                    {
                        "description": "Failover options",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api_dto.FailoverRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_operations.FailoverResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "confirm not set",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "503": {
                        "description": "No eligible replica or quorum not met",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Returns 200 OK when the service can reach the Redis master via Sentinel. Used by Kubernetes readiness probe.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api_dto.HealthResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "503": {
                        "description": "Master unreachable",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "504": {
                        "description": "Redis timeout",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/replication/lag": {
            "get": {
                "description": "Returns the replication offset lag in bytes for every replica, plus a ring-buffer trend of recent samples and a promotion score (0–100, higher = better failover candidate).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "replication"
                ],
                "summary": "Replication lag per replica",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_replication.ReplicaLag"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "502": {
                        "description": "Node unreachable",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "503": {
                        "description": "No master",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/replication/resync-stats": {
            "get": {
                "description": "Returns full-resync counters and backlog utilisation per node. Raises an alert when the backlog exceeds 90% capacity and includes a sizing advisory.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "replication"
                ],
                "summary": "Replication backlog and resync stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_replication.ResyncReport"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "502": {
                        "description": "Node unreachable",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "503": {
                        "description": "No master",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/topology": {
            "get": {
                "description": "Returns the current Master, Replica, and Sentinel node states including per-node health, connected clients, uptime, and quorum status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "topology"
                ],
                "summary": "Get cluster topology",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_sentinel.TopologySnapshot"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "502": {
                        "description": "No sentinel reachable",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "503": {
                        "description": "No master or quorum not met",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "504": {
                        "description": "Redis timeout",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIError"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_duydinhle_redis-sentinel-admin_internal_api.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_api.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_api.APIError"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_api_dto.ChaosFailoverRequest": {
            "description": "Chaos failover trigger parameters",
            "type": "object",
            "properties": {
                "confirm": {
                    "type": "boolean",
                    "example": true
                },
                "mode": {
                    "description": "\"sentinel\"|\"pod\"",
                    "type": "string",
                    "example": "sentinel"
                },
                "pod_name": {
                    "type": "string",
                    "example": "redis-master-0"
                },
                "pod_namespace": {
                    "type": "string",
                    "example": "redis"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_api_dto.ConfigSetRequest": {
            "description": "Redis CONFIG SET parameters",
            "type": "object",
            "properties": {
                "confirm": {
                    "type": "boolean",
                    "example": true
                },
                "key": {
                    "type": "string",
                    "example": "maxmemory-policy"
                },
                "node_addr": {
                    "type": "string",
                    "example": "10.0.0.2:6379"
                },
                "value": {
                    "type": "string",
                    "example": "allkeys-lfu"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_api_dto.FailoverRequest": {
            "description": "Failover trigger options",
            "type": "object",
            "properties": {
                "confirm": {
                    "type": "boolean",
                    "example": true
                },
                "dry_run": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_api_dto.FlushRequest": {
            "description": "Pattern-scoped cluster flush parameters",
            "type": "object",
            "properties": {
                "confirm": {
                    "type": "boolean",
                    "example": true
                },
                "pattern": {
                    "type": "string",
                    "example": "test:*"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_api_dto.HealthResponse": {
            "description": "Service health status",
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_api_dto.SeedRequest": {
            "description": "Dummy data seed parameters",
            "type": "object",
            "properties": {
                "confirm": {
                    "type": "boolean",
                    "example": true
                },
                "key_count": {
                    "type": "integer",
                    "example": 1000
                },
                "key_prefix": {
                    "type": "string",
                    "example": "test:"
                },
                "key_type": {
                    "description": "string|hash|list|set|zset",
                    "type": "string",
                    "example": "string"
                },
                "ttl_sec": {
                    "description": "0 = no expiry",
                    "type": "integer",
                    "example": 3600
                },
                "value_size": {
                    "type": "integer",
                    "example": 256
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_chaos.ChaosFailoverResult": {
            "type": "object",
            "properties": {
                "elapsed_ms": {
                    "type": "integer"
                },
                "mode": {
                    "description": "\"sentinel\" | \"pod\"",
                    "type": "string"
                },
                "target": {
                    "description": "sentinel addr or pod name",
                    "type": "string"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_chaos.FlushResult": {
            "type": "object",
            "properties": {
                "elapsed_ms": {
                    "type": "integer"
                },
                "keys_deleted": {
                    "type": "integer"
                },
                "pattern": {
                    "type": "string"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_chaos.SeedResult": {
            "type": "object",
            "properties": {
                "elapsed_ms": {
                    "type": "integer"
                },
                "key_type": {
                    "type": "string"
                },
                "keys_created": {
                    "type": "integer"
                },
                "prefix": {
                    "type": "string"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_connection.AnalysisResponse": {
            "type": "object",
            "properties": {
                "recommendations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "summary": {
                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_connection.AnalysisSummary"
                },
                "suspicious": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_connection.SuspiciousClient"
                    }
                },
                "top_by_connections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_connection.ClientInfo"
                    }
                },
                "top_by_idle": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_connection.ClientInfo"
                    }
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_connection.AnalysisSummary": {
            "type": "object",
            "properties": {
                "critical_count": {
                    "type": "integer"
                },
                "suspicious_count": {
                    "type": "integer"
                },
                "total_connections": {
                    "type": "integer"
                },
                "unique_clients": {
                    "type": "integer"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_connection.ClientInfo": {
            "type": "object",
            "properties": {
                "conn_count": {
                    "type": "integer"
                },
                "deployment": {
                    "type": "string"
                },
                "max_idle_sec": {
                    "type": "integer"
                },
                "max_qbuf_bytes": {
                    "type": "integer"
                },
                "namespace": {
                    "type": "string"
                },
                "pod_name": {
                    "type": "string"
                },
                "source_addr": {
                    "type": "string"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_connection.NodeConnections": {
            "type": "object",
            "properties": {
                "clients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_connection.ClientInfo"
                    }
                },
                "node_addr": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "suspicious": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_connection.SuspiciousClient"
                    }
                },
                "total": {
                    "type": "integer"
                },
                "unique_clients": {
                    "type": "integer"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_connection.ReplicaDistribution": {
            "type": "object",
            "properties": {
                "node_addr": {
                    "type": "string"
                },
                "overloaded": {
                    "description": "true when this replica carries \u003e80% of total cluster reads",
                    "type": "boolean"
                },
                "read_count": {
                    "type": "integer"
                },
                "read_pct": {
                    "type": "number"
                },
                "total_count": {
                    "type": "integer"
                },
                "write_count": {
                    "type": "integer"
                },
                "write_pct": {
                    "type": "number"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_connection.SuspiciousClient": {
            "type": "object",
            "properties": {
                "deployment": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "pod_name": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "severity": {
                    "description": "warning | critical",
                    "type": "string"
                },
                "source_addr": {
                    "type": "string"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_diagnostics.LockReport": {
            "type": "object",
            "properties": {
                "is_stale": {
                    "description": "true: no TTL or TTL \u003e stale threshold",
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "node_addr": {
                    "type": "string"
                },
                "size_bytes": {
                    "type": "integer"
                },
                "ttl_seconds": {
                    "description": "-1 = no TTL set",
                    "type": "integer"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_diagnostics.MemoryReport": {
            "type": "object",
            "properties": {
                "aof_alert": {
                    "description": "true when last aof rewrite failed",
                    "type": "boolean"
                },
                "aof_enabled": {
                    "type": "boolean"
                },
                "aof_last_rewrite_status": {
                    "type": "string"
                },
                "evicted_keys_per_sec": {
                    "description": "delta since last call",
                    "type": "number"
                },
                "evicted_keys_total": {
                    "type": "integer"
                },
                "eviction_policy": {
                    "type": "string"
                },
                "frag_alert": {
                    "description": "true when frag_ratio \u003e 1.5",
                    "type": "boolean"
                },
                "frag_ratio": {
                    "type": "number"
                },
                "max_memory_bytes": {
                    "type": "integer"
                },
                "node_addr": {
                    "type": "string"
                },
                "rdb_alert": {
                    "description": "true when last bgsave failed",
                    "type": "boolean"
                },
                "rdb_changes_since_save": {
                    "type": "integer"
                },
                "rdb_enabled": {
                    "type": "boolean"
                },
                "rdb_last_bgsave_status": {
                    "type": "string"
                },
                "rdb_last_save_time": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "used_memory_bytes": {
                    "type": "integer"
                },
                "used_memory_human": {
                    "type": "string"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_diagnostics.PipelineReport": {
            "type": "object",
            "properties": {
                "exec_abort_count": {
                    "description": "EXECABORT errors since node start",
                    "type": "integer"
                },
                "max_input_buffer_bytes": {
                    "description": "client_recent_max_input_buffer",
                    "type": "integer"
                },
                "node_addr": {
                    "type": "string"
                },
                "oversized_pipelines": {
                    "description": "clients with qbuf \u003e 1 MiB",
                    "type": "integer"
                },
                "rejected_calls": {
                    "description": "commands rejected (errors/limits)",
                    "type": "integer"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_diagnostics.SlowlogEntry": {
            "type": "object",
            "properties": {
                "args": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "client_addr": {
                    "type": "string"
                },
                "client_name": {
                    "type": "string"
                },
                "duration_us": {
                    "description": "execution time in microseconds",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "node_addr": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_keys.HotKeyReport": {
            "type": "object",
            "properties": {
                "frequency": {
                    "description": "OBJECT FREQ value",
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "node_addr": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_keys.NamespaceTTLReport": {
            "type": "object",
            "properties": {
                "namespace": {
                    "type": "string"
                },
                "no_ttl_alert": {
                    "description": "true when \u003e50% of keys have no TTL",
                    "type": "boolean"
                },
                "no_ttl_keys": {
                    "type": "integer"
                },
                "no_ttl_pct": {
                    "description": "percentage of keys with no TTL",
                    "type": "number"
                },
                "total_keys": {
                    "type": "integer"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_operations.AuditEntry": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "new_value": {
                    "type": "string"
                },
                "node_addr": {
                    "type": "string"
                },
                "old_value": {
                    "type": "string"
                },
                "remote_ip": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_operations.ConfigDiff": {
            "type": "object",
            "properties": {
                "is_drift": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "values": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_operations.NodeConfigValue"
                    }
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_operations.FailoverResult": {
            "type": "object",
            "properties": {
                "dry_run": {
                    "type": "boolean"
                },
                "elapsed_ms": {
                    "type": "integer"
                },
                "new_master": {
                    "type": "string"
                },
                "old_master": {
                    "type": "string"
                },
                "pre_checks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "selected_replica": {
                    "type": "string"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_operations.NodeConfigValue": {
            "type": "object",
            "properties": {
                "node_addr": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_replication.LagSample": {
            "type": "object",
            "properties": {
                "at": {
                    "type": "string"
                },
                "lag_bytes": {
                    "type": "integer"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_replication.ReplicaLag": {
            "type": "object",
            "properties": {
                "is_caught_up": {
                    "description": "lag \u003c 1 MiB",
                    "type": "boolean"
                },
                "lag_bytes": {
                    "type": "integer"
                },
                "lag_trend": {
                    "description": "up to 10 most recent samples",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_replication.LagSample"
                    }
                },
                "master_offset": {
                    "type": "integer"
                },
                "node_addr": {
                    "type": "string"
                },
                "promotion_score": {
                    "description": "0–100, higher = better failover candidate",
                    "type": "number"
                },
                "replica_offset": {
                    "type": "integer"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_replication.ResyncReport": {
            "type": "object",
            "properties": {
                "advisory": {
                    "type": "string"
                },
                "backlog_active_size_bytes": {
                    "type": "integer"
                },
                "backlog_alert": {
                    "description": "active \u003e 90% of backlog size",
                    "type": "boolean"
                },
                "backlog_size_bytes": {
                    "type": "integer"
                },
                "node_addr": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "total_resyncs": {
                    "type": "integer"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_sentinel.NodeInfo": {
            "type": "object",
            "properties": {
                "addr": {
                    "type": "string"
                },
                "connected_clients": {
                    "type": "integer"
                },
                "is_healthy": {
                    "type": "boolean"
                },
                "role": {
                    "description": "\"master\" | \"replica\" | \"sentinel\"",
                    "type": "string"
                },
                "uptime_seconds": {
                    "type": "integer"
                }
            }
        },
        "github_com_duydinhle_redis-sentinel-admin_internal_sentinel.TopologySnapshot": {
            "type": "object",
            "properties": {
                "captured_at": {
                    "type": "string"
                },
                "master": {
                    "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_sentinel.NodeInfo"
                },
                "quorum_ok": {
                    "type": "boolean"
                },
                "replicas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_sentinel.NodeInfo"
                    }
                },
                "sentinels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_duydinhle_redis-sentinel-admin_internal_sentinel.NodeInfo"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Redis Sentinel Admin API",
	Description:      "Monitoring and operations API for Redis Sentinel clusters on Kubernetes.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
