// Redis Sentinel Admin — entry point.
//
//	@title			Redis Sentinel Admin API
//	@version		1.0
//	@description	Monitoring and operations API for Redis Sentinel clusters on Kubernetes.
//	@contact.name	Internal Infra Team
//	@host			localhost:8080
//	@BasePath		/api/v1
//	@schemes		http
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	_ "github.com/duydinhle/redis-sentinel-admin/docs/swagger" // generated by swag init
	"github.com/duydinhle/redis-sentinel-admin/internal/api"
	"github.com/duydinhle/redis-sentinel-admin/internal/api/handlers"
	"github.com/duydinhle/redis-sentinel-admin/internal/config"
	"github.com/duydinhle/redis-sentinel-admin/internal/connection"
	"github.com/duydinhle/redis-sentinel-admin/internal/diagnostics"
	"github.com/duydinhle/redis-sentinel-admin/internal/k8s"
	"github.com/duydinhle/redis-sentinel-admin/internal/keys"
	"github.com/duydinhle/redis-sentinel-admin/internal/sentinel"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
)

func main() {
	configPath := flag.String("config", "config.yaml", "path to config file")
	flag.Parse()

	cfg, err := config.Load(*configPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to load config: %v\n", err)
		os.Exit(1)
	}

	logger, err := buildLogger(cfg.LogLevel)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to build logger: %v\n", err)
		os.Exit(1)
	}
	defer logger.Sync() //nolint:errcheck

	logger.Info("starting redis-sentinel-admin",
		zap.Strings("sentinel_addrs", cfg.SentinelAddrs),
		zap.String("master_name", cfg.MasterName),
		zap.Int("http_port", cfg.HTTPPort),
	)

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	// ── Sentinel layer ────────────────────────────────────────────────────────
	sentinelSvc := sentinel.NewTopologyService(cfg, logger)
	bus := sentinel.NewEventBus()
	pubSubListener := sentinel.NewPubSubListener(cfg, bus, logger)
	go pubSubListener.Run(ctx)

	// ── K8s layer (optional) ──────────────────────────────────────────────────
	podCache := k8s.NewPodCache()
	var throttle *k8s.ThrottleChecker

	k8sClient, k8sErr := k8s.BuildK8sClient()
	if k8sErr != nil {
		logger.Warn("K8s client unavailable — pod IP mapping and throttle check disabled",
			zap.Error(k8sErr))
	} else {
		go func() {
			if err := k8s.StartPodInformer(ctx, k8sClient, cfg.K8sNamespace, podCache); err != nil {
				logger.Warn("pod informer stopped", zap.Error(err))
			}
		}()
		throttle = k8s.NewThrottleChecker(podCache, logger)
	}

	// ── Domain services ───────────────────────────────────────────────────────
	connSvc := connection.New(cfg, sentinelSvc, podCache, throttle, logger)
	diagSvc := diagnostics.New(cfg, sentinelSvc, logger)
	keysSvc := keys.New(cfg, sentinelSvc, logger)

	// ── HTTP server ───────────────────────────────────────────────────────────
	srv := api.New(cfg, logger)
	api.RegisterRoutes(srv.Echo(), api.Deps{
		Healthz:     handlers.Healthz(),
		Readyz:      handlers.Readyz(sentinelSvc),
		GetTopology: handlers.GetTopology(sentinelSvc),
		EventStream: handlers.EventStream(bus),

		GetConnections:  handlers.GetConnections(connSvc),
		GetDistribution: handlers.GetDistribution(connSvc),
		GetSlowlog:      handlers.GetSlowlog(diagSvc),
		GetPipeline:     handlers.GetPipelineStats(diagSvc),

		GetMemory:     handlers.GetMemory(diagSvc),
		StreamBigkeys: handlers.StreamBigkeys(keysSvc),
		GetHotkeys:    handlers.GetHotkeys(keysSvc),
		GetTTLReport:  handlers.GetTTLReport(keysSvc),

		Logger: logger,
	})

	serverErr := make(chan error, 1)
	go func() { serverErr <- srv.Start() }()

	logger.Info("ready",
		zap.String("swagger_ui", fmt.Sprintf("http://localhost:%d/swagger/index.html", cfg.HTTPPort)),
		zap.String("topology", fmt.Sprintf("http://localhost:%d/api/v1/topology", cfg.HTTPPort)),
	)

	select {
	case <-ctx.Done():
		logger.Info("shutdown signal received")
	case err := <-serverErr:
		if err != nil {
			logger.Error("server error", zap.Error(err))
		}
	}

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		logger.Error("graceful shutdown failed", zap.Error(err))
	}
	logger.Info("stopped")
}

func buildLogger(level string) (*zap.Logger, error) {
	var lvl zapcore.Level
	if err := lvl.UnmarshalText([]byte(level)); err != nil {
		lvl = zapcore.InfoLevel
	}
	cfg := zap.NewProductionConfig()
	cfg.Level = zap.NewAtomicLevelAt(lvl)
	cfg.EncoderConfig.EncodeTime = zapcore.ISO8601TimeEncoder
	return cfg.Build()
}
